### ISSUE TITLE
Bug: Fails segfault on dedict

### ISSUE THREAD

**Issue by james-see** [Vik2015/apple-dictionary#3]
```
# jc @ MacBook-Pro-7 in ~/projects/apple-dictionary on git:master x [15:04:06]
$ ./dedict "/System/Library/AssetsV2/com_apple_MobileAsset_DictionaryServices_dictionaryOSX/d87bd03bf66e4abab62953c1015a29f0352a14a0.asset/AssetData/New Oxford American Dictionary.dictionary/Contents/Resources" | ./strip | ./checkxml.py > dictionary.xml
[1]    94892 segmentation fault  ./dedict  |
       94893 done                ./strip |
       94894 done                ./checkxml.py > dictionary.xml
```

I tried editing makefile etc, and I can't figure it out so far. Seems to be something with zlib. 

Mac OS 13.2.1 16-inch 2019 MacBook Pro

**Comment by james-see** [comment]
Any follow up on this?

**Comment by JadedTuna** [comment]
Hey, I'll take a look at this in the coming week.

**Comment by JadedTuna** [comment]
I've checked it, and the code works for me. I think your issue is that you provide `.../Contents/Resources` as the file to dedict, rather than `.../Contents/Resources/Body.data`. Feel free to reopen if you encounter the issue with the correct path.

**Comment by james-see** [comment]
@JadedTuna Ha, it worked. Thank you!
